In [1]:
import random
import string
import numpy as np

In [2]:
# 使用 random.random() 生成一个 0.0 到 1.0 的随机浮点数（左闭右开）
a = random.random()
a

0.11100498389735924

In [3]:
# 使用 random.uniform(a,b) 生成一个指定范围内的随机符点数，两个参数其中一个是上限，一个是下限
# 如果a > b，则生成的随机数 n: b <= n <= a
# 如果 a <b， 则 a <= n <= b
a = random.uniform(1,10)
b = random.uniform(10,1)
a,b

(2.273253518888774, 5.674359775385747)

In [4]:
# 使用 random.randint(a,b) 生成一个指定范围内的整数
# 参数a是下限，参数b是上限，生成的随机数 n: a <= n <= b
a = random.randint(1,10)
a

9

In [5]:
# 使用 random.randrange([start], stop[, step]) 从指定范围内，按指定基数递增的集合中获取一个随机数（左闭右开）
# 随机选取0到100间的偶数
a = random.randrange(0, 101, 2)
a

28

In [6]:
# 使用 random.choice(sequence) 从序列中获取一个随机元素
temp_list = ['AC米兰','曼城','上海申花']  
temp_str = ('我是中国人')  
a = random.choice(temp_list)
b = random.choice(temp_str)
a,b

('上海申花', '中')

In [7]:
# 使用 random.shuffle(x[, random]) 将一个列表中的元素打乱，即将列表内的元素随机排列
a = random.shuffle(temp_list) 
temp_list

['上海申花', '曼城', 'AC米兰']

In [8]:
# 使用 random.sample(sequence, k) 从指定序列中随机获取指定长度的片断并随机排列
# sample 函数不会修改原有序列
a = random.sample(temp_list,2)
a

['上海申花', 'AC米兰']

In [9]:
# 从 a-zA-Z0-9 生成指定数量的随机字符：
a = ''.join(random.sample(string.ascii_letters + string.digits, 8))
a

't60cXMGA'

In [10]:
# 多个字符中选取指定数量的字符组成新字符串：
a = ''.join(random.sample(['z','y','x','w','v','u','t','s','r','q','p','o','n','m','l','k','j','i','h','g','f','e','d','c','b','a'], 5))
a

'bkzdc'

In [11]:
# 随机值
np.random.rand(3,2)

array([[0.40979686, 0.45448756],
       [0.36539892, 0.05304435],
       [0.63898222, 0.19750728]])

In [12]:
# 返回一个样本，具有标准正态分布
np.random.randn()

-0.6324990814656981

In [13]:
# 返回随机的整数，位于半开区间 [low, high)
np.random.randint(2, size=10)

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0])

In [14]:
np.random.randint(5, size=(2, 4))

array([[1, 0, 1, 3],
       [4, 2, 1, 0]])

In [15]:
# 返回随机的整数，位于闭区间 [low, high]
np.random.random_integers(5)

D:\software\anaconda\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  


3

In [17]:
np.random.random_integers(5, size=(3,2))

D:\software\anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  """Entry point for launching an IPython kernel.


array([[4, 4],
       [4, 2],
       [4, 1]])

In [18]:
# 返回随机的浮点数，在半开区间 [0.0, 1.0)
np.random.random_sample()

0.9645422968746241

In [19]:
np.random.random_sample((5,))

array([0.43362715, 0.77190501, 0.17905903, 0.32376346, 0.19613171])

In [20]:
# 生成一个随机样本，从一个给定的一维数组
np.random.choice(5, 3)

array([2, 1, 3])

In [21]:
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 0, 3])

In [22]:
np.random.choice(5, 3, replace=False)

array([4, 1, 3])

In [23]:
np.random.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 3, 0])

In [26]:
np.random.choice(temp_list, 3, p=[0.5, 0.1, 0.4])

array(['AC米兰', 'AC米兰', '上海申花'], dtype='<U4')

In [27]:
# 返回随机字节
np.random.bytes(10)

b'\x9b\xces\x08\x16\xee\x14\x823\xab'

In [29]:
# 现场修改序列，改变自身内容（类似洗牌，打乱顺序）
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([0, 6, 8, 5, 2, 1, 3, 9, 7, 4])

In [30]:
# 返回一个随机排列
np.random.permutation(10)

array([4, 7, 5, 8, 9, 6, 2, 0, 3, 1])

In [31]:
np.random.permutation([1, 4, 9, 12, 15])

array([12, 15,  1,  4,  9])

In [32]:
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])